version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    ports:
      - "5432:5432"

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/website
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
